### ISSUE TITLE
Figure out a place for issues & discussions

### ISSUE THREAD

**Issue by ErikApption** [seamusdemora/RonR-RPi-image-utils#3]
The only place mentioned in the readme for discussions is dead
![image](https://user-images.githubusercontent.com/3179656/208311031-35e9de50-83ba-4eae-9a70-fac7abfd1ced.png)

**Comment by Bertaz** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=332000

**Comment by seamusdemora** [comment]
@ErikApption 

Apologies for the delayed response. I've not really had any issues until this one. I see that @Bertaz has answered your question, and this has prompted me to update the README file so this is hopefully now clear. Again - this isn't my code, and originally wasn't even my repo. I assumed responsibility for it because scruss had gotten bored with it, and I had already written a script to check the forum for updates, and "convert" the .zip files into a repo format.
